### ISSUE TITLE
invisible text

### ISSUE THREAD

**Issue by solstag** [mozillascience/working-open-workshop#68] opened 2016-05-25 15:54 UTC
This is kinda silly but the page at

http://mozillascience.github.io/working-open-workshop/

does not render correctly on Firefox.

Works fine in Epiphany.

**Comment by abbycabs** [comment] 2016-05-30 19:29
Thanks for the issue @solstag! Can you add a screenshot? It works fine for me

**Comment by solstag** [comment] 2016-05-30 20:09
Sure, I'm running Firefox 46.0.1 on Fedora 23.
![capture d ecran de 2016-05-30 22-03-34](https://cloud.githubusercontent.com/assets/27959/15657658/18eb9b12-26b3-11e6-8361-9fb221a919ab.png)

**Comment by abbycabs** [comment] 2016-05-30 20:42
Ah, I think this might be related to the fira sans on linux issue:
https://github.com/mozilla/science.mozilla.org/issues/19

Thanks for filing this!

**Comment by xmatthewx** [comment] 2016-10-17 17:37
@pomax @cadecairos @gideonthomas – can you help investigate this bug when you have a spare moment? Seems to happen on Linux.

**Comment by solstag** [comment] 2016-10-31 14:45
Firefox 49.0 seems to render it properly.

**Comment by Pomax** [comment] 2016-10-31 16:21
if 49 works fine I'm tempted to say "nice!" and call it a day - I was going to suggest updating to the latest stable first, to make sure that the rendering issue wasn't caused by any bugs in FF itself rather than by any code we wrote, and it looks like that fixes things already.

**Comment by abbycabs** [comment] 2016-11-03 17:07
I'm good with calling this a day if it's working in the current release! Closing -- we can reopen if someone else still has this problem :)

**Closed as completed by abbycabs** 2016-11-03 17:07 UTC
Labels: bug
